version: "3.7"

services:
    php-fpm:
        build:
            context: ../
            dockerfile: './docker/php/Dockerfile'
        networks:
            - frontend
            - backend
#        volumes:
#            - ../:/var/www/beat
        environment:
            - APP_ENV=dev
            - BITLY_TOKEN=a60be5024a8ff4b5adf83299d169e4410488ff73
            - REBRANDLY_TOKEN=dc2fa4bac1364c988ebd773664e0ef2b
    apache:
        build:
            context: ../
            dockerfile: './docker/apache/Dockerfile'
        depends_on:
            - php-fpm
            - redis
        networks:
            - frontend
            - backend
        ports:
            - "8787:80"
#        volumes:
#            - ../:/var/www/beat
    redis:
        build: './redis'
        networks:
            - frontend
            - backend
        ports:
            - "6379:6379"
        volumes:
            - redis:/data
networks:
    backend:
        driver: "bridge"
    frontend:
        driver: "bridge"

volumes:
    redis:
